name = "docs-markdown-viewer"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
# You'll need to set these via wrangler secret put
# GOOGLE_CREDENTIALS = "your-service-account-json-here"

[[env.production.routes]]
pattern = "your-domain.com/*"
zone_name = "your-domain.com"

# For development
[env.development]
name = "docs-markdown-viewer-dev"

# Environment variables that can be set via wrangler secret put
# Run these commands after deployment:
# wrangler secret put GOOGLE_CREDENTIALS --env production
# wrangler secret put GOOGLE_CREDENTIALS --env development
